spring.application.name=career-mail-agent

server.port=8080

logging.level.root=INFO
logging.level.io.github.algonawaz=INFO

scheduler.interval=600000

gmail.user-id=me

spring.config.import=optional:application-local.properties


gmail.client-id=${CLIENT_ID}
gmail.client-secret=${CLIENT_SECRET}
gmail.refresh-token=${REFRESH_TOKEN}

telegram.bot-token=${TELEGRAM_BOT_TOKEN}
telegram.chat-id=${TELEGRAM_CHAT_ID}