spring.application.name=career-mail-agent

server.port=8080

logging.level.root=INFO
logging.level.io.github.algonawaz=INFO

scheduler.interval=600000

gmail.user-id=me

spring.config.import=optional:application-local.properties