name: Career Mail Agent

on:
  schedule:
    - cron: "*/15 * * * *"
  workflow_dispatch:

jobs:
  career-mail-agent:

    runs-on: ubuntu-latest

    steps:

      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup Java 25
        uses: actions/setup-java@v4
        with:
          distribution: oracle
          java-version: '25'
          cache: maven

      - name: Make Maven Wrapper Executable
        run: chmod +x mvnw

      - name: Run Career Mail Agent
        env:
          CLIENT_ID: ${{ secrets.CLIENT_ID }}
          CLIENT_SECRET: ${{ secrets.CLIENT_SECRET }}
          REFRESH_TOKEN: ${{ secrets.REFRESH_TOKEN }}
          TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
          TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}
        run: ./mvnw spring-boot:run